trigger:
- master

variables:
- name: BROWSERSTACK_USER
  value: $(BROWSERSTACK_USERNAME)  # Pipeline variable or secret
- name: BROWSERSTACK_ACCESS
  value: $(BROWSERSTACK_ACCESS_KEY)  # Pipeline variable or secret

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true
  displayName: "Set Python Version"

- script: |
    # Install Python dependencies
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Install Python Dependencies"

- script: |
    # Run Appium tests
    echo "Using BrowserStack Username: $BROWSERSTACK_USER"
    echo "Using BrowserStack Access Key: $BROWSERSTACK_ACCESS"
    cd android
    browserstack-sdk python3 browserstack_sample.py
  displayName: 'Run Appium Tests'
  env: # Pass environment variables explicitly
    BROWSERSTACK_USER: $(BROWSERSTACK_USER)
    BROWSERSTACK_ACCESS: $(BROWSERSTACK_ACCESS)
