trigger:
- master

variables:
  BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
  BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true
  displayName: "Set Python Version"

- script: |
    # Install Python dependencies
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Install Python Dependencies"

- script: |
    # Run Appium tests
    cd android
    browserstack-sdk python3 browserstack_sample.py
  displayName: 'Run Appium Tests'