trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true
  displayName: "Set Python Version"
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '10.x'
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'browserstack-sa'

- script: |
    # Install Python dependencies
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Install Python Dependencies"

- script: |
    # Run Appium tests
    cd android
    browserstack-sdk python3 browserstack_sample.py
  displayName: 'Run Appium Tests'