trigger:
- master

variables:
  BROWSERSTACK_USER: $(BROWSERSTACK_USERNAME) # Reference secret variable
  BROWSERSTACK_ACCESS: $(BROWSERSTACK_ACCESS_KEY) # Reference secret variable

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true
  displayName: "Set Python Version"

- script: |
    # Install Python dependencies
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Install Python Dependencies"

- script: |
    # Replace placeholders in browserstack.yml with environment variable values
    sed -e "s|\$BROWSERSTACK_USER|$BROWSERSTACK_USER|g" \
        -e "s|\$BROWSERSTACK_ACCESS|$BROWSERSTACK_ACCESS|g" \
        browserstack.yml > browserstack_runtime.yml

    echo "browserstack_runtime.yml created successfully:"
    cat browserstack_runtime.yml

    # Run tests with the modified browserstack_runtime.yml
    cd android
    browserstack-sdk python3 browserstack_sample.py --config ../browserstack_runtime.yml
  displayName: 'Run Appium Tests'
  env: # Pass secret variables to the script environment
    BROWSERSTACK_USER: $(BROWSERSTACK_USER)
    BROWSERSTACK_ACCESS: $(BROWSERSTACK_ACCESS)
